export type SvgKoreaAdministrativeDistrictIdType =
  | "busan"
  | "daegu"
  | "daejeon"
  | "gangwon"
  | "gwangju"
  | "gyeonggi"
  | "incheon"
  | "jeju"
  | "north-chungcheong"
  | "north-gyeongsang"
  | "north-jeolla"
  | "sejong"
  | "seoul"
  | "south-chungcheong"
  | "south-gyeongsang"
  | "south-jeolla"
  | "ulsan"

export type SvgKoreaAdministrativeDistrictNameType =
  | "부산광역시"
  | "대구광역시"
  | "대전광역시"
  | "강원도"
  | "광주광역시"
  | "경기도"
  | "인천광역시"
  | "제주도"
  | "충청북도"
  | "경상북도"
  | "전라북도"
  | "세종시"
  | "서울특별시"
  | "충청남도"
  | "경상남도"
  | "전라남도"
  | "울산광역시"
