export type SvgKoreaAdministrativeDistrictIdType =
  | "busan"
  | "daegu"
  | "daejeon"
  | "gangwon"
  | "gwangju"
  | "gyeonggi"
  | "incheon"
  | "jeju"
  | "north-chungcheong"
  | "north-gyeongsang"
  | "north-jeolla"
  | "sejong"
  | "seoul"
  | "south-chungcheong"
  | "south-gyeongsang"
  | "south-jeolla"
  | "ulsan"

export type SvgKoreaAdministrativeDistrictNameType =
  | "부산"
  | "대구"
  | "대전"
  | "강원"
  | "광주"
  | "경기"
  | "인천"
  | "제주"
  | "충북"
  | "경북"
  | "전북"
  | "세종"
  | "서울"
  | "충남"
  | "경남"
  | "전남"
  | "울산"
