import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@styles/globals.css"
import GlobalNavigationBar from "@components/navigationBar/templates/GlobalNavigationBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Da-Niim",
  description: "Generated by Da-Niim",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <main>
          <GlobalNavigationBar />
          {children}
        </main>
      </body>
    </html>
  )
}
