import HeaderNavigationBar from "@components/navigationBar/templates/HeaderNavigationBar"
import SideNavigationBar from "@components/navigationBar/templates/SideNavigationBar"
import "@styles/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Providers from "./providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Da-Niim",
  description: "Generated by Da-Niim",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <main>
          <div className="flex flex-col w-screen h-screen">
            <HeaderNavigationBar />
            <div className="flex flex-1">
              <div className="hidden md:flex">
                <SideNavigationBar />
              </div>
              <Providers>
              <div className="flex flex-1">{children}</div>
              </Providers>
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
