const MOCK_DATA = [
  {
    postId: 1,
    userId: 1,
    username: "Tiffi de Banke",
    email: "tde0@prweb.com",
    gender: "Female",
    userimg: "https://robohash.org/ipsumsaepedolores.png?size=50x50&set=set1",
    img: "http://dummyimage.com/192x100.png/cc0000/ffffff",
    address: "California",
    title: "Tango Whiskey Quebec Juliett Echo Alfa Uniform Oscar Foxtrot X-ray India Kilo Romeo Lima November Charlie",
    main: "Southwest Washington Regional Airport",
    tag: "US",
    heart: "88-252-0408",
    comment: "08-053-0141",
    best: true,
  },
  {
    postId: 2,
    userId: 2,
    username: "Theo Furlong",
    email: "tfurlong1@reverbnation.com",
    gender: "Male",
    userimg: "https://robohash.org/reiciendisisteiusto.png?size=50x50&set=set1",
    img: "http://dummyimage.com/174x100.png/dddddd/000000",
    address: "Arizona",
    title: "Hotel Alfa India Juliett Tango Golf Mike Foxtrot Echo Charlie Kilo Lima Delta",
    main: "Solapur Airport",
    tag: "IN",
    heart: "47-562-2076",
    comment: "03-089-9891",
    best: false,
  },
  {
    postId: 3,
    userId: 3,
    username: "Yale Freeborne",
    email: "yfreeborne2@newyorker.com",
    gender: "Male",
    userimg: "https://robohash.org/nammollitiadolores.png?size=50x50&set=set1",
    img: "http://dummyimage.com/192x100.png/dddddd/000000",
    address: "Delaware",
    title:
      "India Echo Kilo Victor November Whiskey Charlie Mike Sierra Bravo Quebec Hotel Uniform Delta Alfa Papa Tango Romeo Golf Yankee",
    main: "Barksdale Air Force Base",
    tag: "US",
    heart: "20-647-8205",
    comment: "35-363-3212",
    best: false,
  },
  {
    postId: 4,
    userId: 4,
    username: "Chane McClements",
    email: "cmcclements3@godaddy.com",
    gender: "Male",
    userimg: "https://robohash.org/doloresvoluptatesdolor.png?size=50x50&set=set1",
    img: "http://dummyimage.com/240x100.png/5fa2dd/ffffff",
    address: "Texas",
    title: "Papa Oscar Quebec Lima Alfa Sierra Delta Yankee Tango Romeo X-ray Bravo Victor Kilo Golf Hotel November",
    main: "King Mswati III International Airport",
    tag: "SZ",
    heart: "96-310-0177",
    comment: "87-519-6762",
    best: true,
  },
  {
    postId: 5,
    userId: 5,
    username: "Jaquelyn Brodhead",
    email: "jbrodhead4@free.fr",
    gender: "Female",
    userimg: "https://robohash.org/veloditquibusdam.png?size=50x50&set=set1",
    img: "http://dummyimage.com/234x100.png/cc0000/ffffff",
    address: "Virginia",
    title:
      "Victor Tango Golf November Bravo Kilo Charlie Papa Echo Yankee Sierra Zulu X-ray Whiskey Hotel Lima Juliett Mike Quebec India",
    main: "Binaka Airport",
    tag: "ID",
    heart: "74-946-3797",
    comment: "36-187-3286",
    best: true,
  },
  {
    postId: 6,
    userId: 6,
    username: "Yvette Beswick",
    email: "ybeswick5@bloglovin.com",
    gender: "Female",
    userimg: "https://robohash.org/natusestvoluptatem.png?size=50x50&set=set1",
    img: "http://dummyimage.com/202x100.png/5fa2dd/ffffff",
    address: "Michigan",
    title:
      "Sierra Golf Oscar Alfa Delta Lima November Victor Yankee Quebec Romeo Charlie Foxtrot Juliett Bravo Whiskey Tango Papa X-ray Mike",
    main: "Eagle River Union Airport",
    tag: "US",
    heart: "52-017-7633",
    comment: "29-243-3765",
    best: false,
  },
  {
    postId: 7,
    userId: 7,
    username: "Bennett Mityashin",
    email: "bmityashin6@edublogs.org",
    gender: "Male",
    userimg: "https://robohash.org/erroreligendiaut.png?size=50x50&set=set1",
    img: "http://dummyimage.com/126x100.png/cc0000/ffffff",
    address: "Utah",
    title: "Quebec Whiskey India Romeo Charlie Hotel Delta X-ray Zulu Alfa Mike Juliett",
    main: "Antwerp International Airport (Deurne)",
    tag: "BE",
    heart: "76-073-3665",
    comment: "22-108-5949",
    best: true,
  },
  {
    postId: 8,
    userId: 8,
    username: "Kalvin Hammerberger",
    email: "khammerberger7@instagram.com",
    gender: "Male",
    userimg: "https://robohash.org/quissintet.png?size=50x50&set=set1",
    img: "http://dummyimage.com/105x100.png/ff4444/ffffff",
    address: "Illinois",
    title: "November Victor X-ray Alfa Delta Foxtrot Sierra Uniform Yankee Tango Charlie Hotel Zulu Quebec",
    main: "Metz-Nancy-Lorraine Airport",
    tag: "FR",
    heart: "06-275-0077",
    comment: "95-126-7558",
    best: true,
  },
  {
    postId: 9,
    userId: 9,
    username: "Barret Trigg",
    email: "btrigg8@who.int",
    gender: "Male",
    userimg: "https://robohash.org/explicaboeiuscupiditate.png?size=50x50&set=set1",
    img: "http://dummyimage.com/130x100.png/cc0000/ffffff",
    address: "Utah",
    title:
      "Whiskey Uniform Charlie Bravo Hotel November Romeo Golf Quebec Mike X-ray Foxtrot India Delta Alfa Zulu Echo Kilo Oscar",
    main: "Kaniama Airport",
    tag: "CD",
    heart: "35-426-5244",
    comment: "47-684-0769",
    best: true,
  },
  {
    postId: 10,
    userId: 10,
    username: "Alyse Kimbly",
    email: "akimbly9@reuters.com",
    gender: "Female",
    userimg: "https://robohash.org/magnieossunt.png?size=50x50&set=set1",
    img: "http://dummyimage.com/135x100.png/5fa2dd/ffffff",
    address: "Oregon",
    title: "Romeo Oscar Kilo Lima Tango November Hotel Mike Yankee Papa Bravo Quebec X-ray Zulu",
    main: "Naypyidaw Airport",
    tag: "MM",
    heart: "09-169-2482",
    comment: "44-572-1324",
    best: false,
  },
  {
    postId: 11,
    userId: 11,
    username: "Casie Revelle",
    email: "crevellea@rambler.ru",
    gender: "Female",
    userimg: "https://robohash.org/doloresquamomnis.png?size=50x50&set=set1",
    img: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    address: "Nebraska",
    title:
      "Alfa Golf Papa India Delta Foxtrot Oscar Whiskey Tango Zulu November Juliett Uniform X-ray Mike Sierra Echo Bravo Hotel",
    main: "Bamfield Seaplane Base",
    tag: "CA",
    heart: "33-670-1172",
    comment: "16-846-4273",
    best: false,
  },
  {
    postId: 12,
    userId: 12,
    username: "Phelia Gillespey",
    email: "pgillespeyb@slideshare.net",
    gender: "Female",
    userimg: "https://robohash.org/doloremqueaccusantiumnesciunt.png?size=50x50&set=set1",
    img: "http://dummyimage.com/211x100.png/cc0000/ffffff",
    address: "Indiana",
    title: "Oscar Juliett Tango Uniform Zulu Hotel November Victor Quebec Lima",
    main: "Corvallis Municipal Airport",
    tag: "US",
    heart: "10-453-4301",
    comment: "79-621-5963",
    best: true,
  },
  {
    postId: 13,
    userId: 13,
    username: "Andros Anger",
    email: "aangerc@gnu.org",
    gender: "Male",
    userimg: "https://robohash.org/molestiaeautconsequatur.png?size=50x50&set=set1",
    img: "http://dummyimage.com/166x100.png/dddddd/000000",
    address: "Illinois",
    title:
      "Zulu Tango Mike Golf Delta India Yankee Juliett Alfa Charlie X-ray November Sierra Whiskey Echo Oscar Quebec Bravo Papa Victor",
    main: "Bria Airport",
    tag: "CF",
    heart: "80-000-2796",
    comment: "10-907-1327",
    best: true,
  },
  {
    postId: 14,
    userId: 14,
    username: "Montague Gallone",
    email: "mgalloned@omniture.com",
    gender: "Male",
    userimg: "https://robohash.org/velexid.png?size=50x50&set=set1",
    img: "http://dummyimage.com/223x100.png/ff4444/ffffff",
    address: "Colorado",
    title: "Hotel Oscar Bravo Papa Tango Romeo Yankee Golf Victor Mike Foxtrot",
    main: "Santa Cruz del Quiche Airport",
    tag: "GT",
    heart: "12-668-0815",
    comment: "51-992-4898",
    best: true,
  },
  {
    postId: 15,
    userId: 15,
    username: "Cathlene Gardener",
    email: "cgardenere@desdev.cn",
    gender: "Female",
    userimg: "https://robohash.org/enimexet.png?size=50x50&set=set1",
    img: "http://dummyimage.com/203x100.png/dddddd/000000",
    address: "Washington",
    title:
      "Mike Papa Yankee X-ray Alfa Hotel Oscar November Golf Juliett India Sierra Zulu Lima Romeo Echo Foxtrot Whiskey Tango",
    main: "Evansville Regional Airport",
    tag: "US",
    heart: "86-999-9827",
    comment: "79-728-8752",
    best: false,
  },
  {
    postId: 16,
    userId: 16,
    username: "Cayla MacIlhagga",
    email: "cmacilhaggaf@vk.com",
    gender: "Female",
    userimg: "https://robohash.org/utquiveritatis.png?size=50x50&set=set1",
    img: "http://dummyimage.com/179x100.png/ff4444/ffffff",
    address: "Georgia",
    title:
      "Golf Alfa November Hotel India Romeo Victor Yankee Quebec Delta Mike Bravo Lima Foxtrot Uniform Echo Charlie Juliett Kilo",
    main: "Billund Airport",
    tag: "DK",
    heart: "92-891-0400",
    comment: "17-654-2784",
    best: true,
  },
  {
    postId: 17,
    userId: 17,
    username: "Rafaellle Blaisdell",
    email: "rblaisdellg@fc2.com",
    gender: "Male",
    userimg: "https://robohash.org/iurevoluptatibusvel.png?size=50x50&set=set1",
    img: "http://dummyimage.com/182x100.png/5fa2dd/ffffff",
    address: "Texas",
    title: "Charlie Juliett Victor Delta Echo Hotel Alfa India Kilo Tango Uniform",
    main: "Bloodvein River Airport",
    tag: "CA",
    heart: "06-461-2775",
    comment: "82-806-1144",
    best: false,
  },
  {
    postId: 18,
    userId: 18,
    username: "Grange Heggman",
    email: "gheggmanh@samsung.com",
    gender: "Male",
    userimg: "https://robohash.org/quisquamcupiditatevoluptate.png?size=50x50&set=set1",
    img: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
    address: "Virginia",
    title: "Foxtrot Alfa Echo Victor November Sierra Whiskey Mike Golf Hotel Delta Zulu Papa Lima India Charlie",
    main: "Tambohorano Airport",
    tag: "MG",
    heart: "42-719-1677",
    comment: "45-940-9011",
    best: true,
  },
  {
    postId: 19,
    userId: 19,
    username: "Ada Farrall",
    email: "afarralli@si.edu",
    gender: "Female",
    userimg: "https://robohash.org/eligendiquiaquo.png?size=50x50&set=set1",
    img: "http://dummyimage.com/124x100.png/dddddd/000000",
    address: "New York",
    title: "Quebec X-ray Foxtrot Yankee Hotel Papa Juliett Oscar Lima Echo Victor Bravo Zulu Tango Mike",
    main: "Sentani International Airport",
    tag: "ID",
    heart: "24-699-7697",
    comment: "79-153-1516",
    best: false,
  },
  {
    postId: 20,
    userId: 20,
    username: "Leslie Diddams",
    email: "ldiddamsj@gov.uk",
    gender: "Female",
    userimg: "https://robohash.org/errordeseruntvoluptate.png?size=50x50&set=set1",
    img: "http://dummyimage.com/116x100.png/dddddd/000000",
    address: "New York",
    title: "Romeo Mike November Delta Lima Juliett Alfa Hotel Golf Oscar Echo Kilo Victor Zulu Tango Whiskey",
    main: "San Nicolas De Bari Airport",
    tag: "CU",
    heart: "57-719-9971",
    comment: "09-263-9685",
    best: false,
  },
]
export default MOCK_DATA
