export { ReactComponent as Home } from "./Home.svg"
export { ReactComponent as Feed } from "./Feed.svg"
export { ReactComponent as Post } from "./Post.svg"
export { ReactComponent as Profile } from "./Profile.svg"
export { ReactComponent as Ranking } from "./Ranking.svg"
export { ReactComponent as Search } from "./Search.svg"
export { ReactComponent as Notification } from "./Notification.svg"
export { ReactComponent as Setting } from "./Setting.svg"
